# version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    env_file: "./src/config/.env"
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  minio:
    image: minio/minio:latest
    command: server --address 0.0.0.0:9001 --console-address 0.0.0.0:9000 /data
    environment:
      - MINIO_ROOT_USER=root
      - MINIO_ROOT_PASSWORD=rootroot
      - MINIO_DOMAIN=s3.minio.localhost
    ports:
      - "9001:9001"
      - "9000:9000"
    volumes:
      - minio_data:/data


  minio-create-bucket:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set s3minio http://minio:9001 root rootroot;
      /usr/bin/mc mb s3minio/tetric-online-files;
      /usr/bin/mc anonymous set public s3minio/tetris-online-files;
      exit 0;
      "

volumes:
  data:
  minio_data:
