# version: '3.9'

services:
  base_app: &base_app
    image: maxtet1703/tetris-backend-v1
    entrypoint: /cnb/lifecycle/launcher


  migration:
    <<: *base_app
    container_name: tetris_migrations
    depends_on:
      - postgres
    entrypoint: migrations

  app: &app
    <<: *base_app
    depends_on:
      - migration
      - postgres

  api:
    <<: *app
    entrypoint: start
    expose:
      - 8000
    ports:
      - "8000:8000"

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    env_file: "./config/.env"
    expose:
      - 5432
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:
