[build]
    [[build.env]]
        name = 'BP_CPYTHON_VERSION'
        value = '3.12.*'

exclude = [
    ".venv",
    ".gitignore",
    "invocations",
    ".gitignore",
    "LICENSE",
    "tasks.py",
    ".vscode",
    "docs",
    "docker-compose.yml",
    "src/tests",
    "nginx.d",
    "k8s",
]
