name: Deployment

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
        - name: install ssh keys
          run: |
            install -m 600 -D /dev/null ~/.ssh/id_ed25519
            echo "${{ secrets.PRIVATE_KEY }}" > ~/.ssh/id_ed25519
            ssh-keyscan -H ${{ secrets.HOST }} > ~/.ssh/known_hosts
        - name: connect and pull
          run: |
            ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} /
            "cd ~/project/Tetris_online_backend && git checkout main && git pull origin main && make down && make remove-image && make build && make make up_prod"



