name: Deployment

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
          - name: "Ssh connect and rebuild"
            id: connect-and-rebuild
            uses: tiyee/action-ssh@v1.0.1
            with:
                host: ${{ secrets.HOST }}
                port: ${{ secrets.PORT }}
                username: ${{ secrets.USERNAME }}
                privateKey: ${{ secrets.PRIVATE_KEY }}
                command: |
                    "cd ~/project/Tetris_online_backend";
                    "git checkout main";
                    "git pull origin main";
                    "make down";
                    "make remove-image";
                    "make build";
                    "make up_prod";



