name: Deployment

on:
    push:
        branches:
            - main

jobs:
    register:
        runs-on: ubuntu-latest
        steps:
          - id: checkout
            name: checkout
            uses: actions/checkout@v3

          - name: Login to Docker Hub
            uses: docker/login-action@v3
            with:
              username: ${{ secrets.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_PASSWORD }}

          - id: setup-tools
            name: install tools for build pack
            uses: buildpacks/github-actions/setup-tools@v5.1.0

          - id: setup-pack
            name: install client for build pack
            uses: buildpacks/github-actions/setup-pack@v5.1.0

          - id: package
            name: build image
            run: make build

          - id: push-to-registry
            name: push to registry
            run: docker push maxtet1703/tetris-backend-v1:latest

          - id: image-clear
            name: remove all images
            run: docker rmi --force $(docker images -q)

          - name: Docker Hub logout
            run: docker logout

